sudo: false
language: python
python:
  - 3.8
cache:
  pip: true
  directories:
env:
matrix:
  fast_finish: true
  include:
    - name: "Python 3.8 on Xenial Linux"
      python: 3.8           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.8
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run pytest --cov-report term-missing --cov .
after_success:
  - pip install coveralls
  - coveralls
notifications:
  email:
    - volker.jaenisch@inqbus.de
