sudo: false
# safelist
branches:
  only:
  - master
language: python
python:
  - 3.9
cache:
  pip: true
matrix:
  fast_finish: true
  include:
    - name: "Python 3.9 on Xenial Linux"
      python: 3.9           # this works for Linux but is ignored on macOS or Windows
      dist: xenial          # required for Python >= 3.8
before_install:
  # install uv
  - pip install uv
install:
  # install dependencies from pyproject.toml with  uv
  - uv sync
script:
  - uv run coverage run --source=ELDAmwl -m pytest
after_success:
  - uv run coveralls
notifications:
  email:
    - volker.jaenisch@inqbus.de
    - ina.mattis@dwd.de
