# :::::::::::::::::::
# ELDAmwl
# :::::::::::::::::::
# mwl output file
default:
  FILE_FORMAT_VERSION : 1.0

#  FIXTURES :
#    - FindBscCalibrWindowAsInELDA
#    - FindBscCalibrWindowAsInELDA.find_calibration_window

# :::::::::::::::::::
# Parallel processing
# :::::::::::::::::::
  CPUS : 4
  PARALLEL : True

# :::::::::::::::::::
# Directories
# :::::::::::::::::::
  LOG_PATH : ''
  SIGNAL_PATH : 'data/ELPP_files'
  PRODUCT_PATH : 'data/ELDA_files'
  TEMP_PATH : ''
  PLUGINS_DIR : ''

# :::::::::::::::::::
# database connection
# :::::::::::::::::::
#  DB_SERVER : ''
#  DB_USER : ''
#  DB_PASS : ''
#  DB_DB : ''
# You have to supply a .secrets.yaml file beside this file with the database access secrets shown above!

# :::::::::::::::::::
# Logging
# :::::::::::::::::::

  # The logfiles
  # general log level
  log_level : DEBUG
  # The desired log_level for console output
  log_level_console : INFO
  # The desired log_level for the logfile
  log_level_file : INFO
  # Colors for the log console output (Options see color_log-package)
  log_colors : {
      'DEBUG': 'cyan',
      'INFO': 'green',
      'WARNING': 'yellow',
      'ERROR': 'red',
      'CRITICAL': 'red,bg_white',
  }

  WRITE_EXTENDED_OUTPUT : True
  APPEND_LOG_FILE : False


testing:
  SIGNAL_PATH : 'data/ELPP_files'
