# :::::::::::::::::::
# ELDAmwl
# :::::::::::::::::::
default:

# :::::::::::::::::::
# Rayleigh fit
# :::::::::::::::::::
 # tested widths of the fit window in km
 # WINDOW_WIDTHS : [1.00, 1.25, 1.5, 2.0, 0.75, 3.0, 4.0, 0.50]
  WINDOW_WIDTHS : [1.00, 2.0, 0.50]

# :::::::::::::::::::
# mwl output file
# :::::::::::::::::::
  FILE_FORMAT_VERSION : 1.0

# :::::::::::::::::::
# testing
# :::::::::::::::::::
#  FIXTURES :
#    - FindBscCalibrWindowAsInELDA
#    - FindBscCalibrWindowAsInELDA.find_calibration_window

# :::::::::::::::::::
# Parallel processing
# :::::::::::::::::::
  NUM_CPU : 4
  PARALLEL : False

# :::::::::::::::::::
# Directories
# :::::::::::::::::::
#  LOG_PATH : '/home/ina/Downloads/eldamwl_logs'
  SIGNAL_PATH : 'data/ELPP_files'
  PRODUCT_PATH : 'data/ELDAmwl_files'
  TEMP_PATH : ''
  PLUGINS_DIR : ''
  LOG_PATH : 'data/eldamwl_logs'

# :::::::::::::::::::
# database connection
# :::::::::::::::::::
#  DB_SERVER : ''
#  DB_USER : ''
#  DB_PASS : ''
#  DB_DB : ''
# You have to supply a .secrets.yaml file beside this file with the database access secrets shown above!

# :::::::::::::::::::
# Logging
# :::::::::::::::::::

  # The logfiles
  # general log level
  log_level : DEBUG
  # The desired log_level for console output
  log_level_console : DEBUG
  # The desired log_level for the logfile
  log_level_file : DEBUG
  # Colors for the log console output (Options see color_log-package)
  log_colors : {
      'DEBUG': 'cyan',
      'INFO': 'green',
      'WARNING': 'yellow',
      'ERROR': 'red',
      'CRITICAL': 'red,bg_white',
  }

  WRITE_EXTENDED_OUTPUT : True
  APPEND_LOG_FILE : False

# :::::::::::::::::::
# single-wavelength quality control
#  (flag values are defined in utils.constants.py)
# :::::::::::::::::::
  # screening of negative values
  # values below 0 - data - error * NEG_VALUES_ERR_FACTOR are flagged
  NEG_VALUES_ERR_FACTOR : 2

  # screening for too large errors
  # values with (error > MAX_ALLOWED_REL_ERROR) and (error > MAX_ALLOWED_ABS_ERROR) are flagged
  MAX_ALLOWED_REL_ERROR : {
      0 : 0.1,  # RBSC
      3 : 0.001,  # EBSC
      1 : 0.5,  # EXT
      2 : 1,  # LR
      15: 0.1,  # VLDR
      16: 0.1,  # PLDR
  }
  MAX_ALLOWED_ABS_ERROR : {
      0 : 1E-9,  # RBSC
      3 : 1E-10,  # EBSC
      1 : 1E-6,  # EXT
      2 : 20,  # LR
      15: 0.1,  # VLDR
      16: 0.1,  # PLDR
  }

  # screening for layers with no aerosol
  # values with corresponding backscatter ratio (at 532nm) < MIN_BSC_RATIO are flagged
  MIN_BSC_RATIO : {
      3 : 1.1,  # EBSC, just for testing
      2 : 1.1,  # LR
  }


testing:
  SIGNAL_PATH : 'data/ELPP_files'

