# -*- coding: utf-8 -*-

# those error codes shall be transformed into exceptions, where applicable

#ERROR_INI_FILE_NOT_EXISTS = 1
ERROR_LR_FILE_NOT_EXISTS = 2
#ERROR_SIG_FILE_NOT_EXISTS = 3
ERROR_SG_FILE_NOT_EXISTS = 4
INVALID_MEASUREMENT_ID = 5
#ERROR_LOG_DIR_NOT_EXISTS = 6
#USE_CASE_NOT_IMPLEMENTED = 7
PRODUCT_NOT_IMPLEMENTED = 8
DB_ERROR = 9
#NC_TYPE_ERROR = 10
#CAL_RANGE_HIGHER_THAN_VALID = 11
# NO_LR_VAR = 'Cannot find variable Lidar_Ratio in lr file'
#NO_VALID_POINTS_FOR_CAL = 13
CANNOT_CREATE_MERGED_SIG = 14
# DIFF_VERT_RES = 15
NOISE_OF_FR_TOO_LARGE_FOR_MERGE = 16
NO_PRODUCT_OPTIONS_IN_DB = 17
DIFF_SCAN_ANGLES = 18
MISSING_EXT_SUBPROFILE = 19
ITER_BSC_NOT_CONV = 20
ERR_NOT_ENOUGH_SG_COEFFICIENTS = 21
#ERR_RUNTIME_EXCEPTION = 22
#ERR_INVALID_NB_OF_MC_ITERATIONS = 23
ERR_NO_MC_OPTIONS_FOR_KLETT = 24
NO_STABLE_SOLUTION_FOR_KLETT = 25
MISSING_CHANNEL_ID_IN_NCFILE = 26
NEGATIVE_CALIBRATION_VALUE = 27
WRONG_ELPP_VERSION = 28
MULTIPLE_DEPOL_NOT_YET_IMPLEMENTED = 29
CANNOT_FIND_CORRECT_CHANNEL_IDX_IN_FILE = 30
#ZERO_DETECTION_LIMIT = 31
