name: tests
on:
  # Triggers the workflow on push but only for the main branch
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #-------------------------------------#
      #  Install mercurial                  #
      #-------------------------------------#
      - name: install Rayleigh fit package
        run: hg clone https://${{ secrets.HG_SCC_USER }}:${{ secrets.HG_SCC_PW }}@repositories.imaa.cnr.it/private/rayleigh-fit/ ../rayleigh_fit
      #- name: check rayleigh installed
      #  run: ls -al ..
      #- name: check rayleigh installed
      #  run: ls -al ../rayleigh_fit

      #-------------------------------------#
      #  Check out repo and set up Python   #
      #-------------------------------------#
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          # optional, aber praktisch, damit UV_PYTHON auf 3.9 zeigt
          python-version: "3.9"
          # optional: Caching aktivieren (standard ist auto)
          enable-cache: "auto"

      - name: Install dependencies with uv
        run:
          uv sync

      #------------------------#
      #  Run your actual job   #
      #------------------------#
      - name: Run tests
        run: |
          uv run coverage run --source=ELDAmwl -m pytest
        env:
          env: testing
